import localFont from "next/font/local";
import "./globals.css";
import Header from './../components/header/index';
import Footer from './../components/footer/index';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className="m-0 flex flex-col h-screen">
      <Header />
        <div > {/* Bu kısım video alanını kaplıyor */}
   

          {/* Arka plan videosu */}
        <div className="relative flex-grow w-full h-screen">
        <div className="absolute top-0 left-0 w-full h-full overflow-hidden z-0">
            <video
              className="w-full h-full object-cover"
              src="/media/video/home.mp4"
              autoPlay
              loop
              muted
            />

            {/* Mavi filigran */}
            <div className="absolute top-0 left-0 w-full h-full bg-blue-700 opacity-30"></div>
          </div>

          {/* İçerik */}
          <div className="relative h-full flex flex-col items-center justify-center">
  <h1 className="text-white font-bold text-5xl">
    {Array.from("FATIH YAVUZ").map((char, index) => (
      <span
        key={index}
        className="relative inline-block"
        style={{
          textShadow: '3px 3px 0px #ff6a00', // Turuncu gölge
        }}
      >
        {char === " " ? "\u00A0" : char} {/* Boşluk için özel karakter kullan */}
      </span>
    ))}
  </h1>
  <h2 className="text-white text-2xl">DATA ANALYST | BI ANALYST</h2>
</div>



        </div>

          {/* Çocuk elemanlar */}
          <main className="relative z-10">
            {children}
          </main>
        </div>
        
        <Footer /> {/* Footer burada sabit olarak en alta yerleştirildi */}
      </body>
    </html>
  );
}
